import{initializeApp}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import{getFirestore,doc,setDoc,getDoc,collection,getDocs,query,where,orderBy,limit,startAfter,addDoc,updateDoc,deleteDoc,writeBatch}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAtEyvDp07Ej5KUiRaa6n0HMNrQBo6z33Y",authDomain:"boutme-3d364.firebaseapp.com",projectId:"boutme-3d364",storageBucket:"boutme-3d364.firebasestorage.app",messagingSenderId:"879605364049",appId:"1:879605364049:web:6b1b74869aaf7e00ca4f70",measurementId:"G-M4QQPYK2WT"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),PAGE=10;
const videoColors=['#8f3f46','#b0663c','#a18436','#527a58','#397879','#416b91','#5d5b91','#795284','#9b5572','#52636f','#866849','#466d65'];
const blankData=()=>({slug:'',avatar:'',name:'',shortBio:'',email:'',website:'',telephone:'',longInfo:'',address:'',links:[],statuses:[],videos:[],photos:[],songs:[]});
window.appData=blankData();
let ownerId=null,publicOwnerId=null,cursors={links:null,statuses:null,videos:null,photos:null},more={links:true,statuses:true,videos:true,photos:true},loading={links:false,statuses:false,videos:false,photos:false};

function sanitizeHTML(s){if(!s)return'';return String(s).replace(/[&<>'"]/g,t=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[t]))}
function sanitizeURL(u){if(!u)return'#';u=String(u).trim();return/^(https?:\/\/|mailto:|tel:|data:image\/)/i.test(u)?u:'#'}
function parseYouTubeID(u){if(!u)return null;u=String(u).trim();if(/^[\w-]{11}$/.test(u))return u;const m=u.match(/^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=|shorts\/|live\/)([^#&?]*).*/);return m&&m[2].length===11?m[2]:null}
function videoSeed(v,i){let s=(v.id||'')+(v.title||'')+i,h=0;for(let x=0;x<s.length;x++)h=(h*31+s.charCodeAt(x))>>>0;return(h%10000)/10000}

window.addEventListener('DOMContentLoaded',async()=>{const p=new URLSearchParams(location.search),slug=p.get('slug')||location.hash.replace('#/','').replace('#',''),t=localStorage.getItem('hub_theme');if(t)document.documentElement.setAttribute('data-theme',t);if(slug){authOverlay.style.display='none';backToDashBtn.style.display='none';await loadPublicProfileBySlug(slug.toLowerCase())}});

async function loadPublicProfileBySlug(slug){try{const s=await getDocs(query(collection(db,'users'),where('slug','==',slug),limit(1)));if(s.empty)throw Error('not-found');const snap=s.docs[0];publicOwnerId=snap.id;window.appData={...blankData(),...snap.data()};renderPublicPage()}catch(e){console.error(e);authOverlay.innerHTML=`<div class="auth-card"><h2>Profile Not Found</h2><p>No user profile matches slug: /@${sanitizeHTML(slug)}</p><button class="action-btn" onclick="window.location.href=window.location.pathname">Go to Login</button></div>`;authOverlay.style.display='flex'}}

window.handleLogin=async()=>{const e=loginEmail.value,p=loginPassword.value;if(!e||!p)return alert('Please enter email and password.');try{await signInWithEmailAndPassword(auth,e,p)}catch(x){alert('Login failed: '+x.message)}};
window.handleLogout=async()=>{try{await signOut(auth);location.reload()}catch(e){console.error(e)}};

onAuthStateChanged(auth,async user=>{const p=new URLSearchParams(location.search);if(p.get('slug')||location.hash)return;if(user){authOverlay.style.display='none';dashboardContent.style.display='flex';ownerId=user.uid;await loadUserData(user.uid);await loadAdminCollections(user.uid);initDashboard()}else{authOverlay.style.display='flex';dashboardContent.style.display='none'}});

async function loadUserData(uid){try{const s=await getDoc(doc(db,'users',uid));window.appData={...blankData(),...(s.exists()?s.data():{})}}catch(e){console.error(e);window.appData=blankData()}}
async function loadAdminCollections(uid){try{const [l,s,v,p,m]=await Promise.all([getDocs(query(collection(db,'users',uid,'links'),orderBy('position','asc'))),getDocs(query(collection(db,'users',uid,'statuses'),orderBy('datetime','asc'))),getDocs(query(collection(db,'users',uid,'videos'),orderBy('position','asc'))),getDocs(query(collection(db,'users',uid,'photos'),orderBy('position','desc'))),getDocs(query(collection(db,'users',uid,'songs'),orderBy('position','asc')))]);appData.links=l.docs.map(d=>({_id:d.id,...d.data()}));appData.statuses=s.docs.map(d=>({_id:d.id,...d.data()}));appData.videos=v.docs.map(d=>({_id:d.id,...d.data()}));appData.photos=p.docs.map(d=>({_id:d.id,...d.data()}));appData.songs=m.docs.map(d=>({_id:d.id,...d.data()}))}catch(e){console.error('Could not load dashboard lists:',e);appData.links=[];appData.statuses=[];appData.videos=[];appData.photos=[];appData.songs=[]}}

async function saveProfileCore(){const u=auth.currentUser;if(!u)throw Error('Not signed in');const d={slug:appData.slug,avatar:appData.avatar,name:appData.name,shortBio:appData.shortBio,email:appData.email,website:appData.website,telephone:appData.telephone,longInfo:appData.longInfo,address:appData.address};await setDoc(doc(db,'users',u.uid),d)}
async function syncLinks(){if(!ownerId)return;const existing=await getDocs(collection(db,'users',ownerId,'links')),batch=writeBatch(db);existing.forEach(x=>batch.delete(x.ref));appData.links.forEach((x,i)=>batch.set(doc(collection(db,'users',ownerId,'links')),{label:x.label||'',url:x.url||'',position:i}));await batch.commit();await loadAdminCollections(ownerId)}

window.saveProfileData=async()=>{const s=inputSlug.value.trim().toLowerCase().replace(/[^a-z0-9-_]/g,'');if(!s)return alert('Please enter a valid URL slug.');Object.assign(appData,{slug:s,avatar:inputAvatar.value.trim(),name:inputName.value,shortBio:inputShortBio.value,email:inputEmail.value.trim(),website:inputWebsite.value.trim(),telephone:inputPhone.value,longInfo:inputLongInfo.value,address:inputAddress.value});slugDisplay.innerText=`Slug: /@${s}`;try{await saveProfileCore();await syncLinks();renderDynamicFieldsInputs();renderAdminLists();alert('Profile and links saved!')}catch(e){console.error(e);alert('Failed to save. Check Firestore rules.')}};

window.viewPublicPage=()=>{dashboardContent.style.display='none';publicOwnerId=ownerId;renderPublicPage()};
window.backToDashboard=()=>{publicProfileView.style.display='none';dashboardContent.style.display='flex'};
window.switchDashboardTab=i=>{document.querySelectorAll('#dashboardContent .tab-btn').forEach((b,x)=>b.classList.toggle('active',x===i));document.querySelectorAll('#dashboardContent .tab-panel').forEach((p,x)=>p.classList.toggle('active',x===i))};
window.switchPublicTab=i=>{document.querySelectorAll('#publicProfileView .tab-btn').forEach((b,x)=>b.classList.toggle('active',x===i));document.querySelectorAll('#publicProfileView .tab-panel').forEach((p,x)=>p.classList.toggle('active',x===i));setTimeout(maybeLoadMore,0)};

let publicSongs=[],musicAudio=null,musicIndex=0,musicShuffle=false,musicRepeat=0,musicTile=null;
async function loadPublicSongs(){publicSongs=[];try{const s=await getDocs(query(collection(db,'users',publicOwnerId,'songs'),orderBy('position','asc'),limit(50)));publicSongs=s.docs.map(d=>({_id:d.id,...d.data()}))}catch(e){console.warn('Music playlist unavailable:',e)}}
function openPhoto(p){lightboxImage.src=sanitizeURL(p.image);lightboxTitle.textContent=p.title||'';lightboxDesc.textContent=p.description||'';photoLightbox.classList.add('open');photoLightbox.setAttribute('aria-hidden','false')}
function closePhoto(){photoLightbox.classList.remove('open');photoLightbox.setAttribute('aria-hidden','true');lightboxImage.src=''}
photoLightbox.querySelector('.lightbox-close').onclick=closePhoto;photoLightbox.onclick=e=>{if(e.target===photoLightbox)closePhoto()};addEventListener('keydown',e=>{if(e.key==='Escape')closePhoto()});
function musicLabel(){if(!musicTile)return;const s=publicSongs[musicIndex];musicTile.querySelector('.music-name').textContent=s?.title||'';musicTile.classList.toggle('playing',!!musicAudio&&!musicAudio.paused);musicTile.querySelector('[data-act="play"]').textContent=musicAudio&&!musicAudio.paused?'Ⅱ':'▶';musicTile.querySelector('[data-act="shuffle"]').classList.toggle('on',musicShuffle);musicTile.querySelector('[data-act="repeat"]').classList.toggle('on',musicRepeat>0);musicTile.querySelector('[data-act="repeat"]').textContent=musicRepeat===2?'↻¹':'↻'}
function playSong(i,auto=true){if(!publicSongs.length)return;musicIndex=(i+publicSongs.length)%publicSongs.length;if(musicAudio){musicAudio.pause();musicAudio.src=''}musicAudio=new Audio(sanitizeURL(publicSongs[musicIndex].url));musicAudio.preload='metadata';musicAudio.onended=()=>{if(musicRepeat===2)playSong(musicIndex,true);else if(musicRepeat===1)playSong(musicIndex+1,true);else if(musicShuffle)playSong(Math.floor(Math.random()*publicSongs.length),true);else if(musicIndex<publicSongs.length-1)playSong(musicIndex+1,true);else musicLabel()};musicAudio.onerror=()=>musicLabel();musicLabel();if(auto)musicAudio.play().then(musicLabel).catch(musicLabel)}
function musicAction(a){if(!publicSongs.length)return;if(a==='play'){if(!musicAudio)playSong(musicIndex,true);else if(musicAudio.paused)musicAudio.play().then(musicLabel).catch(()=>{});else{musicAudio.pause();musicLabel()}}else if(a==='prev')playSong(musicIndex-1,true);else if(a==='next')playSong(musicShuffle?Math.floor(Math.random()*publicSongs.length):musicIndex+1,true);else if(a==='shuffle'){musicShuffle=!musicShuffle;musicLabel()}else if(a==='repeat'){musicRepeat=(musicRepeat+1)%3;musicLabel()}}
function makeMusicTile(){const d=document.createElement('article');d.className='music-tile';d.innerHTML='<div class="rush-fx" aria-hidden="true"><i class="fx-line l1"></i><i class="fx-line l2"></i><i class="fx-arc a1"></i><i class="fx-arc a2"></i><i class="fx-ring r1"></i><i class="fx-ring r2"></i><i class="fx-dot d1"></i><i class="fx-dot d2"></i><i class="fx-symbol s1">♥</i><i class="fx-symbol s2">◆</i><i class="fx-symbol s3">♣</i><i class="fx-symbol s4">♠</i></div><div class="music-name"></div><button class="float-control c-prev" data-act="prev" aria-label="Previous">‹</button><button class="float-control c-play" data-act="play" aria-label="Play">▶</button><button class="float-control c-next" data-act="next" aria-label="Next">›</button><button class="float-control c-shuffle" data-act="shuffle" aria-label="Shuffle">⤨</button><button class="float-control c-repeat" data-act="repeat" aria-label="Repeat">↻</button>';d.querySelectorAll('[data-act]').forEach(b=>b.onclick=e=>{e.stopPropagation();musicAction(b.dataset.act)});musicTile=d;musicLabel();return d}
function ensureMusicTile(){if(!pubPhotoWall.querySelector('.music-tile')){const tile=makeMusicTile(),second=pubPhotoWall.children[1];second?pubPhotoWall.insertBefore(tile,second):pubPhotoWall.appendChild(tile)}}
function activatePublicVideo(card,id){const f=card.querySelector('.tv-frame');if(f.querySelector('iframe'))return;f.innerHTML=`<iframe src="https://www.youtube.com/embed/${sanitizeHTML(id)}?autoplay=1&playsinline=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`}
async function fetchPage(type,sort='asc'){if(!publicOwnerId||loading[type]||!more[type])return[];loading[type]=true;try{let q;if(type==='links')q=query(collection(db,'users',publicOwnerId,'links'),orderBy('position','asc'),...(cursors.links?[startAfter(cursors.links)]:[]),limit(PAGE));if(type==='videos')q=query(collection(db,'users',publicOwnerId,'videos'),orderBy('position','asc'),...(cursors.videos?[startAfter(cursors.videos)]:[]),limit(PAGE));if(type==='statuses')q=query(collection(db,'users',publicOwnerId,'statuses'),orderBy('datetime',sort),...(cursors.statuses?[startAfter(cursors.statuses)]:[]),limit(PAGE));if(type==='photos')q=query(collection(db,'users',publicOwnerId,'photos'),orderBy('position','desc'),...(cursors.photos?[startAfter(cursors.photos)]:[]),limit(PAGE));const s=await getDocs(q);if(s.docs.length)cursors[type]=s.docs[s.docs.length-1];if(s.docs.length<PAGE)more[type]=false;return s.docs.map(d=>({_id:d.id,...d.data()}))}catch(e){console.error(type+' pagination failed:',e);more[type]=false;return[]}finally{loading[type]=false}}
async function renderNextLinks(){const rows=await fetchPage('links');rows.forEach(x=>{const a=document.createElement('a');a.className='bio-btn';a.href=sanitizeURL(x.url);a.target='_blank';a.rel='noopener noreferrer';a.textContent=x.label||'Link';pubLinks.appendChild(a)});linksLoadingMsg.textContent=more.links?'Scroll down to load more links...':'All links loaded.'}
async function renderNextVideos(){const rows=await fetchPage('videos'),base=pubWall.children.length;rows.forEach((v,j)=>{const i=base+j,id=parseYouTubeID(v.id)||v.id,seed=videoSeed(v,i),card=document.createElement('article');card.className='tv-box';const color=v.wallColor||videoColors[Math.floor(seed*videoColors.length)%videoColors.length],rot=-2+((seed*9973)%1)*4,scale=.96+((seed*619)%1)*.07,y=-6+((seed*431)%1)*14;card.style.setProperty('--video-card',color);card.style.transform=`rotate(${rot}deg) translateY(${y}px) scale(${scale})`;card.innerHTML=`<div class="tv-frame"><img class="tv-thumb" src="https://i.ytimg.com/vi/${sanitizeHTML(id)}/hqdefault.jpg" alt="" loading="lazy"><div class="tv-play" aria-label="Play video"></div></div><div class="tv-title">${sanitizeHTML(v.title||'Video')}</div>`;card.querySelector('.tv-play').onclick=()=>activatePublicVideo(card,id);pubWall.appendChild(card)});videosLoadingMsg.textContent=more.videos?'Scroll down to load more videos...':'All videos loaded.'}
async function renderNextPhotos(){const rows=await fetchPage('photos');rows.forEach(p=>{const card=document.createElement('article');card.className='photo-card';const img=document.createElement('img');img.className='photo-img';img.loading='lazy';img.alt=p.title||'Photo';img.src=sanitizeURL(p.image);img.onerror=()=>card.classList.add('photo-broken');card.onclick=()=>openPhoto(p);card.appendChild(img);pubPhotoWall.appendChild(card)});ensureMusicTile();photosLoadingMsg.textContent=more.photos?'Scroll down to load more photos...':'All photos loaded.'}
async function renderNextStatuses(){const sort=publicSortOrderSelect.value==='new'?'desc':'asc',rows=await fetchPage('statuses',sort),t=pubThermometerTimeline,old=t.querySelector('.thermometer-base-bulb');if(old)old.remove();let i=t.querySelectorAll('.timeline-item').length;rows.forEach(s=>{const d=document.createElement('div');d.className=`timeline-item ${i++%2?'right':'left'}`;let m='';if(s.url){const id=parseYouTubeID(s.url);m=id?`<div class="media-player-container"><iframe src="https://www.youtube.com/embed/${sanitizeHTML(id)}" loading="lazy" allowfullscreen></iframe></div>`:`<a href="${sanitizeURL(s.url)}" target="_blank" style="display:inline-block;margin-top:8px;color:var(--accent-color);font-size:.85rem;font-weight:bold">🔗 Open Link</a>`}d.innerHTML=`<div class="timeline-content"><span class="date-badge">${sanitizeHTML(s.datetime)}</span><h3 style="font-size:1rem;margin-bottom:4px">${sanitizeHTML(s.title)}</h3><p style="font-size:.85rem;opacity:.9;line-height:1.4">${sanitizeHTML(s.desc)}</p>${m}</div>`;t.appendChild(d)});if(t.children.length){const b=document.createElement('div');b.className='thermometer-base-bulb';t.appendChild(b)}timelineLoadingMsg.textContent=more.statuses?'Scroll down to load more statuses...':'All statuses loaded.'}

function renderPublicPage(){publicProfileView.style.display='flex';publicSlugHeader.innerText=`Public Profile: /@${appData.slug} (Share Link: ${location.origin}${location.pathname}?slug=${appData.slug})`;pubAvatarContainer.innerHTML='';if(appData.avatar){const i=document.createElement('img');i.className='avatar-preview';i.src=sanitizeURL(appData.avatar);pubAvatarContainer.appendChild(i)}else{const d=document.createElement('div');d.className='avatar-preview';d.innerText=appData.name?appData.name.charAt(0):'U';pubAvatarContainer.appendChild(d)}pubName.innerText=appData.name||'';pubShortBio.innerText=appData.shortBio||'';pubLongInfo.innerText=appData.longInfo||'';let c='';if(appData.email)c+=`<div>📧 <b>Email:</b> <a href="mailto:${sanitizeHTML(appData.email)}" style="color:var(--text-color)">${sanitizeHTML(appData.email)}</a></div>`;if(appData.telephone)c+=`<div>📞 <b>Phone:</b> <a href="tel:${sanitizeHTML(appData.telephone)}" style="color:var(--text-color)">${sanitizeHTML(appData.telephone)}</a></div>`;if(appData.website)c+=`<div>🌐 <b>Website:</b> <a href="${sanitizeURL(appData.website)}" target="_blank" style="color:var(--text-color)">${sanitizeHTML(appData.website)}</a></div>`;if(appData.address)c+=`<div>📍 <b>Address:</b> ${sanitizeHTML(appData.address)}</div>`;pubContact.innerHTML=c;pubLinks.innerHTML='';pubWall.innerHTML='';pubPhotoWall.innerHTML='';pubThermometerTimeline.innerHTML='';cursors={links:null,statuses:null,videos:null,photos:null};more={links:true,statuses:true,videos:true,photos:true};loading={links:false,statuses:false,videos:false,photos:false};loadPublicSongs().then(()=>{ensureMusicTile();musicLabel()});renderNextLinks();renderNextVideos();renderNextPhotos();renderNextStatuses()}
window.resetAndRenderPublicTimeline=()=>{pubThermometerTimeline.innerHTML='';cursors.statuses=null;more.statuses=true;loading.statuses=false;renderNextStatuses()};
function near(el){return el&&el.getBoundingClientRect().top<innerHeight+300}
function maybeLoadMore(){if(pubPanel0.classList.contains('active')&&more.links&&near(linksLoadingMsg))renderNextLinks();if(pubPanel1.classList.contains('active')&&more.statuses&&near(timelineLoadingMsg))renderNextStatuses();if(pubPanel2.classList.contains('active')&&more.videos&&near(videosLoadingMsg))renderNextVideos();if(pubPanel3.classList.contains('active')&&more.photos&&near(photosLoadingMsg))renderNextPhotos()}
window.addEventListener('scroll',maybeLoadMore,{passive:true});window.addEventListener('resize',maybeLoadMore,{passive:true});
window.toggleTheme=()=>{const h=document.documentElement,current=h.getAttribute('data-theme'),themes=['very-black','white','chameleon'],n=themes[(themes.indexOf(current)+1)%themes.length];h.setAttribute('data-theme',n);localStorage.setItem('hub_theme',n)};

function initDashboard(){const t=localStorage.getItem('hub_theme');if(t)document.documentElement.setAttribute('data-theme',t);inputSlug.value=appData.slug||'';slugDisplay.innerText=`Slug: /@${appData.slug||''}`;roleIndicator.innerText='Owner';inputAvatar.value=appData.avatar||'';inputName.value=appData.name||'';inputShortBio.value=appData.shortBio||'';inputEmail.value=appData.email||'';inputWebsite.value=appData.website||'';inputPhone.value=appData.telephone||'';inputLongInfo.value=appData.longInfo||'';inputAddress.value=appData.address||'';renderDynamicFieldsInputs();renderAdminLists()}
function renderDynamicFieldsInputs(){dynamicFieldsContainer.innerHTML='';appData.links.forEach((f,i)=>{const r=document.createElement('div');r.style.cssText='display:flex;gap:8px;margin-bottom:8px';r.innerHTML=`<input placeholder="Label" value="${sanitizeHTML(f.label)}" oninput="updateFieldData(${i},'label',this.value)" style="flex:1"><input type="url" placeholder="https://..." value="${sanitizeHTML(f.url)}" oninput="updateFieldData(${i},'url',this.value)" style="flex:1.5"><button class="delete-btn" onclick="removeExtraFieldRow(${i})">X</button>`;dynamicFieldsContainer.appendChild(r)});fieldCountTracker.innerText=appData.links.length}
window.addExtraFieldRow=(label='',url='')=>{appData.links.push({label,url});renderDynamicFieldsInputs()};
window.removeExtraFieldRow=i=>{appData.links.splice(i,1);renderDynamicFieldsInputs()};
window.updateFieldData=(i,k,v)=>appData.links[i][k]=v;

window.saveTimelineMilestone=async()=>{const title=timelineTitle.value.trim(),datetime=timelineDate.value||new Date().toISOString().slice(0,16),desc=timelineDesc.value,url=timelineUrl.value.trim(),i=parseInt(editingTimelineIndex.value);if(!title)return alert('Please enter a status title.');try{if(i>-1){const s=appData.statuses[i];await updateDoc(doc(db,'users',ownerId,'statuses',s._id),{title,datetime,desc,url});cancelEditTimeline()}else{await addDoc(collection(db,'users',ownerId,'statuses'),{title,datetime,desc,url});timelineTitle.value=timelineDate.value=timelineDesc.value=timelineUrl.value=''}await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e);alert('Could not save status. Check Firestore rules.')}};
window.editTimelineMilestone=i=>{const s=appData.statuses[i];timelineTitle.value=s.title||'';timelineDate.value=s.datetime||'';timelineDesc.value=s.desc||'';timelineUrl.value=s.url||'';editingTimelineIndex.value=i;timelineFormHeader.innerText='Edit ThermoTimelineMeter Status';timelineSubmitBtn.innerText='Update Status';timelineCancelBtn.style.display='block'};
window.cancelEditTimeline=()=>{timelineTitle.value=timelineDate.value=timelineDesc.value=timelineUrl.value='';editingTimelineIndex.value='-1';timelineFormHeader.innerText='Add ThermoTimelineMeter Status';timelineSubmitBtn.innerText='Post Status';timelineCancelBtn.style.display='none'};
window.removeTimelineMilestone=async i=>{try{await deleteDoc(doc(db,'users',ownerId,'statuses',appData.statuses[i]._id));cancelEditTimeline();await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e)}};
window.addVideoBoxItem=async()=>{const title=videoTitleInput.value.trim(),raw=videoUrlInput.value.trim();if(!title||!raw)return alert('Please enter a title and YouTube link/ID.');const id=parseYouTubeID(raw);if(!id)return alert('Please enter a valid YouTube link or video ID.');try{await addDoc(collection(db,'users',ownerId,'videos'),{title,id,wallColor:videoColors[Math.floor(Math.random()*videoColors.length)],position:Date.now()});videoTitleInput.value=videoUrlInput.value='';await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e);alert('Could not save video. Check Firestore rules.')}};
window.clearPhotoForm=()=>{photoTitleInput.value=photoDescInput.value=photoUrlInput.value=''};
window.addPhotoItem=async()=>{const title=photoTitleInput.value.trim(),description=photoDescInput.value.trim(),image=photoUrlInput.value.trim();if(!title)return alert('Please enter a photo title.');if(!image)return alert('Please enter a Photo URL.');if(!/^https:\/\//i.test(image))return alert('Photo URL must start with https://');try{await addDoc(collection(db,'users',ownerId,'photos'),{title,description,image,position:Date.now()});clearPhotoForm();await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e);alert(e?.message||'Could not save photo.')}};
window.addPhotoWallSong=async()=>{const title=songTitleInput.value.trim(),url=songUrlInput.value.trim();if(!title||!url)return alert('Please enter a song title and direct audio URL.');if(!/^https:\/\//i.test(url))return alert('Audio URL must start with https://');try{await addDoc(collection(db,'users',ownerId,'songs'),{title,url,position:Date.now()});songTitleInput.value=songUrlInput.value='';await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e);alert('Could not save song. Check Firestore rules.')}};
window.removePhotoWallSong=async i=>{try{await deleteDoc(doc(db,'users',ownerId,'songs',appData.songs[i]._id));await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e)}};
window.removePhotoItem=async i=>{try{await deleteDoc(doc(db,'users',ownerId,'photos',appData.photos[i]._id));await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e)}};
window.removeVideoBoxItem=async i=>{try{await deleteDoc(doc(db,'users',ownerId,'videos',appData.videos[i]._id));await loadAdminCollections(ownerId);renderAdminLists()}catch(e){console.error(e)}};
function renderAdminLists(){timelineManagerList.innerHTML='';if(!appData.statuses.length)timelineManagerList.innerHTML='<div style="opacity:.6;font-size:.85rem">No statuses yet.</div>';appData.statuses.forEach((s,i)=>{const r=document.createElement('div');r.className='item-row';r.innerHTML=`<div><b>${sanitizeHTML(s.title)}</b> <span style="font-size:.75rem;opacity:.6">(${sanitizeHTML(s.datetime)})</span></div><div><button class="edit-btn" onclick="editTimelineMilestone(${i})">Edit</button><button class="delete-btn" onclick="removeTimelineMilestone(${i})">Delete</button></div>`;timelineManagerList.appendChild(r)});videoManagerList.innerHTML='';if(!appData.videos.length)videoManagerList.innerHTML='<div style="opacity:.6;font-size:.85rem">No videos yet.</div>';appData.videos.forEach((v,i)=>{const r=document.createElement('div');r.className='item-row';r.innerHTML=`<div><b>${sanitizeHTML(v.title)}</b></div><button class="delete-btn" onclick="removeVideoBoxItem(${i})">Remove</button>`;videoManagerList.appendChild(r)});photoManagerList.innerHTML='';if(!appData.photos.length)photoManagerList.innerHTML='<div style="opacity:.6;font-size:.85rem">No photos yet.</div>';appData.photos.forEach((p,i)=>{const r=document.createElement('div');r.className='item-row';r.innerHTML=`<div><b>${sanitizeHTML(p.title)}</b></div><button class="delete-btn" onclick="removePhotoItem(${i})">Remove</button>`;photoManagerList.appendChild(r)});songManagerList.innerHTML='';if(!appData.songs.length)songManagerList.innerHTML='<div style="opacity:.6;font-size:.85rem">No songs yet.</div>';appData.songs.forEach((s,i)=>{const r=document.createElement('div');r.className='item-row';r.innerHTML=`<div><b>${sanitizeHTML(s.title)}</b></div><button class="delete-btn" onclick="removePhotoWallSong(${i})">Remove</button>`;songManagerList.appendChild(r)})}
